module.exports.viewAll = function(req, res) {
    const cards = [{
        id: 1,
        pokemonName: 'Pikachu',
        pokemonHealth: '50 HP',
        pokemonType: 'Electric',
        pokemonTypeImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Pok%C3%A9mon_Electric_Type_Icon.svg/480px-Pok%C3%A9mon_Electric_Type_Icon.svg.png',
        pokemonImage: 'https://cdn.shoplightspeed.com/shops/633327/files/29258343/ftla-art-kit-painting-acrylic-pikachu.jpg',
        moveOneImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Pok%C3%A9mon_Electric_Type_Icon.svg/480px-Pok%C3%A9mon_Electric_Type_Icon.svg.png',
        moveOneAmount: 1,
        moveOne: 'Gnaw',
        moveOneDamage: 10,
        moveTwoImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Pok%C3%A9mon_Electric_Type_Icon.svg/480px-Pok%C3%A9mon_Electric_Type_Icon.svg.png',
        moveTwoAmount: 2,
        moveTwo: 'Lightning Shock',
        moveTwoDamage: 50,
        weaknessImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Pok%C3%A9mon_Rock_Type_Icon.svg/1024px-Pok%C3%A9mon_Rock_Type_Icon.svg.png',
        resistanceImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Pok%C3%A9mon_Flying_Type_Icon.svg/2048px-Pok%C3%A9mon_Flying_Type_Icon.svg.png',
        retreatCostImage: 'https://cdn.pixabay.com/photo/2018/05/20/21/00/pokemon-3416764_1280.png',
        retreatCostAmount: 2,
    },
        {
            id: 2,
            pokemonName: 'Charizard',
            pokemonHealth: '120 HP',
            pokemonType: 'Fire',
            pokemonTypeImage: 'https://www.clipartmax.com/png/full/83-830894_fire-type-pokemon-symbol-pokemon-fire-type-logo.png',
            pokemonImage: 'https://images.saymedia-content.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cq_auto:eco%2Cw_1200/MTc2MjkyNDg2MzI1NDc4NTkw/pokemon-charizard-nicknames.png',
            moveOneImage: 'https://www.clipartmax.com/png/full/83-830894_fire-type-pokemon-symbol-pokemon-fire-type-logo.png',
            moveOneAmount: 0,
            moveOne: 'Energy Burn',
            moveOneDamage: 0,
            moveTwoImage: 'https://www.clipartmax.com/png/full/83-830894_fire-type-pokemon-symbol-pokemon-fire-type-logo.png',
            moveTwoAmount: 4,
            moveTwo: 'Fire Spin',
            moveTwoDamage: 100,
            weaknessImage: 'https://www.nicepng.com/png/full/810-8104664_rethink-the-bottle-water-energy-symbol.png',
            resistanceImage: 'https://www.pngkit.com/png/full/353-3532588_pokemon-fighting-type-symbol-pokemon-card-fighting-energy.png',
            retreatCostImage: 'https://cdn.pixabay.com/photo/2018/05/20/21/00/pokemon-3416764_1280.png',
            retreatCostAmount: 3,
            backgroundColor: '#e59534',
        }];
    res.render('index', {cards});
};