module.exports.viewAll = function(req, res) {
    const cards = [{
        id: 1,
        pokemonName: 'Pikachu',
        pokemonHealth: '50 HP',
        pokemonType: 'Electric',
        pokemonTypeImage: 'http://pm1.narvii.com/5867/6c6a05dde0693c1dfe454912c83109f165f3f7ab_00.jpg',
        pokemonImage: 'https://cdn.shoplightspeed.com/shops/633327/files/29258343/ftla-art-kit-painting-acrylic-pikachu.jpg',
        moveOneImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Pok%C3%A9mon_Electric_Type_Icon.svg/480px-Pok%C3%A9mon_Electric_Type_Icon.svg.png\'',
        moveOneAmount: 1,
        moveOne: 'Gnaw',
        moveOneDamage: 10,
        moveTwoImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Pok%C3%A9mon_Electric_Type_Icon.svg/480px-Pok%C3%A9mon_Electric_Type_Icon.svg.png\'',
        moveTwoAmount: 2,
        moveTwo: 'Lightning Shock',
        moveTwoDamage: 50,
        weaknessImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Pok%C3%A9mon_Rock_Type_Icon.svg/1024px-Pok%C3%A9mon_Rock_Type_Icon.svg.png',
        resistanceImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Pok%C3%A9mon_Flying_Type_Icon.svg/2048px-Pok%C3%A9mon_Flying_Type_Icon.svg.png',
        retreatCostImage: 'https://cdn.pixabay.com/photo/2018/05/20/21/00/pokemon-3416764_1280.png',
        retreatCostAmount: 2,
    },
    {
        id: 2,
        pokemonName: 'Charizard',
        pokemonHealth: '120 HP',
        pokemonType: 'Fire',
        pokemonTypeImage: 'https://www.pngfind.com/pngs/m/501-5010420_pokemon-fire-type-symbol-png-transparent-png.png',
        pokemonImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/131.png',
        moveOneImage: 'https://www.giantbomb.com/a/uploads/scale_medium/16/164924/3083931-8746743194-flat%2C.jpg',
        moveOneAmount: 0,
        moveOne: 'Energy Burn',
        moveOneDamage: 0,
        moveTwoImage: 'https://www.giantbomb.com/a/uploads/scale_medium/16/164924/3083931-8746743194-flat%2C.jpg',
        moveTwoAmount: 4,
        moveTwo: 'Fire Spin',
        moveTwoDamage: 100,
        weaknessImage: 'https://www.nicepng.com/png/full/810-8104664_rethink-the-bottle-water-energy-symbol.png',
        resistanceImage: 'https://image.emojipng.com/644/8585644.jpg',
        retreatCostImage: 'https://cdn.pixabay.com/photo/2018/05/20/21/00/pokemon-3416764_1280.png',
        retreatCostAmount: 3,
        backgroundColor: '#e59534',
        }];
    res.render('index', {cards});
};